### ISSUE TITLE
setBrowser.js  this.buffer.setUint8 arguments are reversed

### ISSUE THREAD

**Issue by andyvandy** [ThreeLetters/SimpleProtocols#1]
in setBrowser.js (and likely a couple other places) we have : 

this.buffer.setUint8( n, this.index++)

When it should be

this.buffer.setUint8( this.index++, n)

I think this error stems from the fact that in Node the value comes first and the index second whereas in javascript it's reversed.

**Comment by Andrews54757** [comment]
Thanks
